export const API_REAL_TIME_ENDPOINT = process.env.NEXT_PUBLIC_API_REAL_TIME_ENDPOINT ?? "";
export const API_GRAPHQL_ENDPOINT = process.env.NEXT_PUBLIC_API_GRAPHQL_ENDPOINT ?? "";
export const AWS_REGION = process.env.NEXT_PUBLIC_AWS_REGION ?? "us-east-2";
export const COGNITO_USERPOOL_ID = process.env.NEXT_PUBLIC_COGNITO_USERPOOL_ID ?? "";
export const COGNITO_USERPOOL_WEBCLIENT_ID = process.env.NEXT_PUBLIC_COGNITO_USERPOOL_WEBCLIENT_ID ?? "";
export const COGNITO_IDENTITYPOOL_ID = process.env.NEXT_PUBLIC_COGNITO_IDENTITYPOOL_ID ?? "";
